version: "3.7"

services:
  detect:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=detect.config.DevelopmentConfig
